name: Auto-Merge PR with GH CLI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  enable-automerge:
    runs-on: ubuntu-latest

    steps:

      - name: Get Pull Request ID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_OWNER=$(echo ${{ github.repository }} | cut -d'/' -f1)
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          PR_NUMBER=${{ github.event.pull_request.number }}

          QUERY=$(cat <<EOF
          {
            "query": "query { repository(name: \\"$REPO_NAME\\", owner: \\"$REPO_OWNER\\") { pullRequest(number: $PR_NUMBER) { id } } }"
          }
          EOF
          )

          echo "$QUERY"

          RESPONSE=$(curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$QUERY" https://api.github.com/graphql)

          echo "$RESPONSE"

          PR_ID=$(echo $RESPONSE | jq -r '.data.repository.pullRequest.id')

          echo "Pull Request ID: $PR_ID"

          if [ "$PR_ID" == "null" ] || [ -z "$PR_ID" ]; then
            echo "Failed to retrieve Pull Request ID."
            exit 1
          fi

          echo "PR_ID=$PR_ID" >> $GITHUB_ENV

      - name: Enable Auto-Merge
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # Use a PAT with repo and workflow scopes.
          PR_ID: ${{ env.PR_ID }}
        run: |
          MUTATION=$(cat <<EOF
          {
            "query": "mutation { enablePullRequestAutoMerge(input: {pullRequestId: \\"$PR_ID\\", mergeMethod: MERGE}) { clientMutationId } }"
          }
          EOF
          )

          echo "$MUTATION"

          RESPONSE=$(curl -s -X POST -H "Authorization: Bearer $MY_GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$MUTATION" https://api.github.com/graphql)

          echo "Auto-Merge Response: $RESPONSE"

          if [[ $RESPONSE == *"errors"* ]]; then
            echo "Failed to enable auto-merge."
            exit 1
          fi

      - name: Confirm Auto-Merge Enabled
        run: echo "Auto-Merge has been successfully enabled for the Pull Request."